theme: minima
title: "ScheduleBud User Guide: Hidden Features & Pro Tips"
description: "Get the most out of your ScheduleBud trial and subscription with these power user secrets"
url: "https://schedulebud.tech"
baseurl: ""

# SEO and social
author: Tony
youtube_username: schedule_bud
github_username: schedulebud

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Page defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"